name: GitHub Actions Demo
 
on: 
  push:
    branches: [ main ]
    paths-ignore: ['.github']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron:  '15 6 * * 0'
  workflow_dispatch:
  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build Solution
        run: |
          echo Event: ${{ github.event_name }}
          echo Branch: ${{ github.ref_name }}
          echo Files:
          find .
