name: GitHub Actions Demo
 
on: 
  push:
    branches: [ main ]
    paths-ignore: ['.github/**']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron:  '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'Production'
        options:
          - 'Production'
          - 'Test'
          - 'Test-Load'
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build Solution
        run: |
          echo Event: ${{ github.event_name }}
          echo Branch: ${{ github.ref_name }}
          echo Files:
          find .

  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' 
    needs: build
    environment: Test
    steps:
      - run: echo "Testing..."
      
  load-test:
    name: Load Test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' 
    needs: build
    environment: Load-Test
    steps:
      - run: |
          echo "Testing..."
          sleep 15

  production:
    name: Production
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    needs: [test, load-test]
    steps:
      - run: |
          echo "Step 1..."
          sleep 10
      - run: |
          echo "Step 2..."
          sleep 10
      - run: |
          echo "Step 3..."
          sleep 10
      - run: |
          echo "Step 4..."
          sleep 10
      - run: |
          echo "Step 5..."
          sleep 10
